FWF-3324: [Feature] Added permmision mapping to roles
AOT-Technologies/forms-flow-ai-micro-front-ends pull request #223
Opened 2024-06-11 09:08 UTC by Ajay-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-3324
Issue Type:  FEATURE

# Changes
1.API call added for fetching permissions
2.Added permmision mapping to roles
3.Translation is added

# Screenshots

![image](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/assets/115780710/9393a6fd-82ce-4622-b891-2fade1e50998)
![image](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/assets/115780710/019c7dd5-f62a-4a3e-8b44-189175f73dca)
![image](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/assets/115780710/77ef86dc-3e62-4a95-8fdd-cfabe838dc67)
![image](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/assets/115780710/a6e666f6-ac9b-472f-b3ce-37a7dfbb6aec)

2024-06-18 07:54 UTC, arun-s-aot requested changes
- Instead of removing the code, please comment the existing code. 
- Add data test id, aria-label to newly added form components. 
- Rename 'handleCheckboxChange' to 'handlePermissionCheck'. 
- Rename 'handleEditCheckboxChange' to 'handleEditPermissionCheck'

2024-06-19 06:34 UTC, Ajay-aot commented
> * Instead of removing the code, please comment the existing code.
> * Add data test id, aria-label to newly added form components.
> * Rename 'handleCheckboxChange' to 'handlePermissionCheck'.
> * Rename 'handleEditCheckboxChange' to 'handleEditPermissionCheck'

changes added @arun-s-aot

2024-06-24 06:39 UTC, arun-s-aot approved these changes

2024-06-27 07:25 UTC, Josephalexantony-aot approved these changes

2024-06-27 08:59 UTC, merged