Feature/fwf-435 permission matrix Navbar & Admin module
AOT-Technologies/forms-flow-ai-micro-front-ends pull request #233
Opened 2024-07-01 19:21 UTC by fahad-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-3435
Issue Type: BUG/ FEATURE

# Changes
1. Navbar changes 
2. Admin module permission changes

2024-07-02 05:30 UTC, Josephalexantony-aot approved these changes

2024-07-02 05:44 UTC, Bonymol-aot approved these changes

2024-07-08 07:40 UTC, arun-s-aot requested changes
Please set userRoles.includes(<permissions>) to different variables and use that variables in html conditions . 

Ex : Instead of userRoles.includes("create_submissions") , set it to variable named  canCreateSubmissions .

2024-07-08 08:27 UTC, fahad-aot commented
> Please set userRoles.includes() to different variables and use that variables in html conditions .
> 
> Ex : Instead of userRoles.includes("create_submissions") , set it to variable named canCreateSubmissions .

ok

2024-07-10 05:27 UTC, arun-s-aot approved these changes

2024-07-10 05:27 UTC, merged