Feature/fwf 3426 navigation changes
AOT-Technologies/forms-flow-ai-micro-front-ends pull request #240
Opened 2024-07-19 09:06 UTC by Ajay-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-3426
Issue Type: BUG/ FEATURE

# Changes
1.New navigation changes
2.permission matrix changes added

2024-07-21 16:39 UTC, arun-s-aot commented on forms-flow-nav/src/sidenav/hamburger.scss
Avoid writing same css selector multiple times. (Ex : .custom-navbar )
Avoid writing duplicate media query tags with same breakpoint

2024-07-21 16:44 UTC, arun-s-aot commented on forms-flow-nav/src/sidenav/Sidebar.scss
Please move the root variables to theme.scss file which can be used commonly in other pages

2024-07-21 16:48 UTC, arun-s-aot requested changes
Please make changes as per the comments

2024-07-22 04:22 UTC, Josephalexantony-aot commented on forms-flow-nav/src/sidenav/Sidebar.scss
Use the colors from the color system instead of using direct hexadecimal or HSL

2024-07-23 09:45 UTC, Ajay-aot commented on forms-flow-nav/src/sidenav/Sidebar.scss
done

2024-07-23 09:45 UTC, Ajay-aot commented on forms-flow-nav/src/sidenav/hamburger.scss
done

2024-07-24 08:21 UTC, arun-s-aot approved these changes

2024-07-24 08:50 UTC, Josephalexantony-aot approved these changes

2024-07-24 08:55 UTC, merged