changed svg to component
AOT-Technologies/forms-flow-ai-micro-front-ends pull request #241
Opened 2024-07-22 15:03 UTC by abilpraju-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE
https://aottech.atlassian.net/browse/FWF-3510
![image](https://github.com/user-attachments/assets/2cbedac3-6fd7-4d26-80a1-9d069bd5dea1)

2024-07-23 04:48 UTC, Josephalexantony-aot approved these changes

2024-07-23 04:53 UTC, Josephalexantony-aot requested changes
alt="Access Denied Icon"
 This alt text will lead to accessibility issues, 
 just give "Access Denied"
 [ logo, icon, image... such words in alt text will create accessibility break].

2024-07-23 04:55 UTC, shuhaib-aot approved these changes

2024-07-23 04:55 UTC, shuhaib-aot commented on forms-flow-admin/src/components/AccessDenied/index.js
> +      <AccessDeniedIcon  alt="Access Denied Icon" className="mb-4 mt-2" />
follow the alex comment

2024-07-24 04:35 UTC, arun-s-aot approved these changes

2024-07-24 04:36 UTC, arun-s-aot approved these changes

2024-07-24 04:36 UTC, merged