style changes  for choose template modal
AOT-Technologies/forms-flow-ai-micro-front-ends pull request #280
Opened 2024-09-24 15:10 UTC by fahad-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes
1.style changes for template modal

2024-09-25 11:51 UTC, arun-s-aot commented on forms-flow-theme/scss/_modal.scss
> +    border-bottom: 1px solid var(--gray-gray-0, #F2F2F3);
duplicate style. please remove 1

2024-09-26 03:58 UTC, arun-s-aot requested changes
Please change the css variables to use from the theme scss file. Lof the variables used here are not present in the system @fahad-aot

2024-09-27 08:28 UTC, Bonymol-aot approved these changes

2024-09-30 06:38 UTC, fahad-aot commented on forms-flow-theme/scss/_modal.scss
> +    border-bottom: 1px solid var(--gray-gray-0, #F2F2F3);
updated

2024-10-03 08:07 UTC, arun-s-aot approved these changes

2024-10-03 08:07 UTC, merged